name: Run R Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '**'

jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up R
      uses: r-lib/actions/setup-r@v2

    - name: Install system dependencies
      run: |
        sudo apt-get install -y libcurl4-openssl-dev libssl-dev libgit2-dev

    - name: Install R package dependencies
      run: |
        install.packages('remotes')
        remotes::install_github('r-lib/gitcreds')

    - name: Set up GitHub PAT
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gitcreds::gitcreds_set()

    - name: Install Hector package
      run: |
        remotes::install_github('jgcri/hector')

    - name: Check
      run: |
        Rscript -e 'remotes::install_github("jgcri/hector")'
